apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/component: message-broker
  name: rabbitmq-system
