apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/component: message-broker
  name: rabbitmq-cluster-nodes
  namespace: rabbitmq-system
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: cluster-rpc
    port: 25672
    protocol: TCP
    targetPort: 25672
  publishNotReadyAddresses: true

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/component: message-broker
  name: rabbitmq-client
  namespace: rabbitmq-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
  ports:
  - appProtocol: amqp
    name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/component: message-broker
  name: rabbitmq-management
  namespace: rabbitmq-system
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
  ports:
  - appProtocol: http
    name: management
    port: 15672
    protocol: TCP
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/component: message-broker
  name: rabbitmq-metrics
  namespace: rabbitmq-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
  ports:
  - appProtocol: prometheus.io/metrics
    name: metrics
    port: 15692
    protocol: TCP
    targetPort: 15692