apiVersion: v1
data:
  rabbitmq-default-user: UmFiYml0QDEyMw==
  rabbitmq-default-pass: UmFiYml0QDEyMw==
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-cluster-secret
  namespace: rabbitmq-system
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/component: message-broker

---
apiVersion: v1
data:
  .erlang.cookie: NkVJUENRUUhSNUx4UFlRaGxQU0dpVEIzVVNYOWpJNFY=
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-cluster-erlang-cookie
  namespace: rabbitmq-system
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: messaging-system
    app.kubernetes.io/component: message-broker

